// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk3LfL9ysg56alJWi8vsg13HwdtVEyFL4',
    appId: '1:610954968866:web:bd29687b4aa6d302256f7b',
    messagingSenderId: '610954968866',
    projectId: 'anchal-project',
    authDomain: 'anchal-project.firebaseapp.com',
    storageBucket: 'anchal-project.appspot.com',
    measurementId: 'G-CZKDER8TMJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-tV83-Bih77RoYm4846sCyUNmdu6bXv0',
    appId: '1:610954968866:android:58ec2ae079b11d95256f7b',
    messagingSenderId: '610954968866',
    projectId: 'anchal-project',
    storageBucket: 'anchal-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiEiUyTpd0GbGSV8z0ea_VQREvbP4K1SM',
    appId: '1:610954968866:ios:bae6a9c7cf7cef9f256f7b',
    messagingSenderId: '610954968866',
    projectId: 'anchal-project',
    storageBucket: 'anchal-project.appspot.com',
    iosClientId:
        '610954968866-ov3lpjl9gsiucaj8b2u7fr63jdlrsdab.apps.googleusercontent.com',
    iosBundleId: 'com.kosidev.mentalHealthCareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiEiUyTpd0GbGSV8z0ea_VQREvbP4K1SM',
    appId: '1:610954968866:ios:f079a091150fa84f256f7b',
    messagingSenderId: '610954968866',
    projectId: 'anchal-project',
    storageBucket: 'anchal-project.appspot.com',
    iosClientId:
        '610954968866-23m3h5vnruem6ejn2ppisj4quaq4itgh.apps.googleusercontent.com',
    iosBundleId: 'com.example.mentalHealthCareApp',
  );
}
